name: flash_chat
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  modal_progress_hud_nsn: ^0.4.0
  shared_preferences: ^2.1.2
  fluttertoast: ^8.2.2
  firebase_messaging: ^14.6.4
  flutter_local_notifications: ^14.1.1
  rxdart: ^0.27.7
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - images/

